import type {
  ProcedureFixTemplate,
  PublishedProcedurePack,
  PublishedProcedureTemplate,
} from './airportOperations';

const ACCESSED_ON = '2026-08-24';

const dohaFixGeometry: Record<string, [number, number]> = {
  AFNAN: [122.3, 16.8],
  ALKAN: [44.9, 25.7],
  BAYAN: [40.6, 14],
  DASIK: [183.6, 14.1],
  DATAL: [87.7, 26.1],
  DINEX: [122.3, 22.8],
  EGNUG: [65.9, 9.9],
  EMALO: [114.9, 15.5],
  EMEXA: [180.9, 17],
  GETOV: [50.3, 22.2],
  GINTO: [269.4, 18.2],
  GOKNI: [217.9, 18.5],
  HAYYA: [346.9, 25.2],
  IMGOG: [352.8, 15.7],
  IMTAL: [143.2, 18.5],
  IVANI: [357.6, 13.8],
  KATED: [312.6, 14],
  KINAP: [246.1, 12.4],
  KIPEM: [162.1, 17.2],
  KIPIK: [244.9, 10.6],
  KIVAM: [132.9, 20.1],
  KUBAR: [75.2, 21.5],
  KUTER: [207.4, 13.8],
  KUVLA: [101.4, 24.2],
  LABEX: [81.7, 23.5],
  LAEEB: [187.6, 20.5],
  LAGNO: [269.3, 14.7],
  LOSEN: [300.3, 12.3],
  LOVAN: [131.2, 12.2],
  LOVET: [67.9, 13.2],
  LUBAK: [40.6, 17.5],
  MISOX: [109.3, 10.6],
  MIVAL: [196.6, 15],
  MURGO: [283, 18.4],
  MUTLI: [95.1, 13.8],
  MUXED: [139, 13.8],
  NADIG: [246.7, 14.3],
  NOKTO: [273.8, 10.9],
  NOLMA: [25, 10.6],
  NONBA: [215.4, 13.2],
  NORMU: [77.6, 28.5],
  ORLEK: [280, 27],
  OXAGO: [59.3, 18.8],
  PURIN: [193, 12.6],
  PUTAN: [6.8, 12],
  RESAR: [63.9, 24.5],
  RUBOL: [206.8, 16.4],
  SENKI: [44.5, 22.8],
  SIDMU: [122.1, 11.3],
  SILBI: [71.1, 26.3],
  SOMAP: [201.2, 11.8],
  TONBI: [330.4, 16.1],
  TOSNA: [90, 28.5],
  TOVOX: [117.5, 25.2],
  TUDOM: [36.2, 21.1],
  UKOBA: [134.7, 17],
  UKTON: [224, 14.9],
  VEDED: [10.2, 25.6],
  VELAM: [9.8, 21.5],
  VUTAN: [22.8, 20.8],
};

type DohaFixSpec = [
  id: string,
  minimumAltitudeFt?: number,
  maximumAltitudeFt?: number,
  maximumSpeedKt?: number,
];

function dohaFix([id, minimumAltitudeFt, maximumAltitudeFt, maximumSpeedKt]: DohaFixSpec): ProcedureFixTemplate {
  const geometry = dohaFixGeometry[id];
  if (!geometry) throw new Error(`Missing Doha geometry for ${id}`);
  return {
    id, bearing: geometry[0], distanceNm: geometry[1],
    ...(minimumAltitudeFt === undefined ? {} : { minimumAltitudeFt }),
    ...(maximumAltitudeFt === undefined ? {} : { maximumAltitudeFt }),
    ...(maximumSpeedKt === undefined ? {} : { maximumSpeedKt }),
  };
}

function dohaArrival(id: string, runwayIds: string[], fixes: DohaFixSpec[]): PublishedProcedureTemplate {
  return {
    id, kind: 'arrival', compatibleRunwayIds: runwayIds,
    entryTransition: fixes[0]![0], fixes: fixes.map(dohaFix),
  };
}

const dohaRouteSpecs: Array<[string, string[], DohaFixSpec[]]> = [
  ['ALKAN1F', ["16L","16R"], [['ALKAN', 20000, undefined, undefined], ['GETOV', undefined, undefined, 250], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', 7000, 7000, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['HAYYA1F', ["16L","16R"], [['HAYYA', 21000, undefined, undefined], ['VELAM', 19000, undefined, undefined], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', 7000, 7000, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['HAYYA1K', ["16L","16R"], [['HAYYA', 21000, undefined, undefined], ['TONBI', 19000, undefined, undefined], ['MURGO', 16000, 16000, undefined], ['GINTO', undefined, undefined, undefined], ['LAGNO', undefined, undefined, undefined], ['NADIG', undefined, undefined, undefined], ['UKTON', undefined, undefined, undefined], ['RUBOL', undefined, undefined, undefined], ['DASIK', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', undefined, undefined, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['VEDED1F', ["16L","16R"], [['VEDED', 18000, 18000, undefined], ['VELAM', undefined, undefined, 250], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', 7000, 7000, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['ALKAN2H', ["16L","16R"], [['ALKAN', 20000, undefined, undefined], ['SENKI', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['HAYYA2H', ["16L","16R"], [['HAYYA', 21000, undefined, undefined], ['VELAM', 19000, undefined, undefined], ['VUTAN', 18000, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 3500, undefined, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['VEDED2H', ["16L","16R"], [['VEDED', 18000, 18000, undefined], ['VUTAN', 18000, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['ALKAN1P', ["16L","16R"], [['ALKAN', 20000, undefined, undefined], ['GETOV', undefined, undefined, 250], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['HAYYA1P', ["16L","16R"], [['HAYYA', 21000, undefined, undefined], ['VELAM', 19000, undefined, undefined], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['TOSNA1T', ["16L","16R"], [['TOSNA', 20000, undefined, undefined], ['DATAL', undefined, undefined, undefined], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['VEDED1P', ["16L","16R"], [['VEDED', 18000, 18000, undefined], ['VELAM', undefined, undefined, 250], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 8000, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['LAEEB2F', ["16L","16R"], [['LAEEB', 17000, undefined, undefined], ['EMEXA', 13000, 13000, undefined], ['DASIK', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', undefined, undefined, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['LAEEB2K', ["16L","16R"], [['LAEEB', 17000, undefined, undefined], ['GOKNI', 13000, 13000, undefined], ['GINTO', undefined, undefined, undefined], ['LAGNO', undefined, undefined, undefined], ['NADIG', undefined, undefined, undefined], ['UKTON', undefined, undefined, undefined], ['RUBOL', undefined, undefined, undefined], ['DASIK', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', undefined, undefined, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['ORLEK2F', ["16L","16R"], [['ORLEK', 21000, undefined, undefined], ['GINTO', 15000, 15000, undefined], ['LAGNO', undefined, undefined, undefined], ['NADIG', undefined, undefined, undefined], ['UKTON', undefined, undefined, undefined], ['RUBOL', undefined, undefined, undefined], ['DASIK', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', undefined, undefined, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['TOSNA2F', ["16L","16R"], [['TOSNA', 20000, undefined, undefined], ['KUVLA', undefined, undefined, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, undefined, undefined], ['IMTAL', undefined, undefined, undefined], ['KIPEM', 11000, 12000, undefined], ['EMEXA', 10000, 10000, undefined], ['DASIK', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', undefined, undefined, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['TOVOX2F', ["16L","16R"], [['TOVOX', 18000, 18000, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, undefined, undefined], ['IMTAL', undefined, undefined, undefined], ['KIPEM', 11000, 12000, undefined], ['EMEXA', 10000, 10000, undefined], ['DASIK', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['KIPIK', undefined, undefined, undefined], ['NOKTO', undefined, undefined, undefined], ['LOSEN', undefined, undefined, undefined], ['KATED', 2500, 3500, 220]]],
  ['LAEEB1P', ["16L","16R"], [['LAEEB', 17000, undefined, undefined], ['RUBOL', undefined, undefined, undefined], ['DASIK', 12000, 12000, undefined], ['MUXED', undefined, undefined, undefined], ['SIDMU', 8000, undefined, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['ORLEK1P', ["16L","16R"], [['ORLEK', 21000, undefined, undefined], ['GINTO', 15000, 15000, undefined], ['LAGNO', undefined, undefined, undefined], ['NADIG', undefined, undefined, undefined], ['UKTON', undefined, undefined, undefined], ['RUBOL', undefined, undefined, undefined], ['DASIK', 12000, 12000, undefined], ['MUXED', undefined, undefined, undefined], ['SIDMU', 8000, undefined, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['TOSNA1P', ["16L","16R"], [['TOSNA', 20000, undefined, undefined], ['KUVLA', undefined, undefined, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, undefined, 250], ['UKOBA', 11000, 11000, undefined], ['MUXED', undefined, undefined, undefined], ['SIDMU', 8000, undefined, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['TOVOX2P', ["16L","16R"], [['TOVOX', 18000, 18000, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, undefined, 250], ['UKOBA', 11000, 11000, undefined], ['MUXED', undefined, undefined, undefined], ['SIDMU', 8000, undefined, undefined], ['EGNUG', undefined, undefined, undefined], ['NOLMA', undefined, undefined, undefined], ['PUTAN', undefined, undefined, undefined], ['IVANI', 2500, 3500, 220], ['IMGOG', undefined, undefined, undefined]]],
  ['ALKAN2L', ["34L","34R"], [['ALKAN', 20000, undefined, undefined], ['GETOV', undefined, undefined, 250], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['KATED', undefined, undefined, undefined], ['LOSEN', 11000, 11000, 230], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['HAYYA1J', ["34L","34R"], [['HAYYA', 21000, undefined, undefined], ['TONBI', 19000, undefined, undefined], ['MURGO', 16000, undefined, undefined], ['GINTO', undefined, undefined, undefined], ['LAGNO', 10000, 10000, undefined], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['HAYYA2L', ["34L","34R"], [['HAYYA', 21000, undefined, undefined], ['VELAM', 19000, undefined, undefined], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['KATED', undefined, undefined, undefined], ['LOSEN', 11000, 11000, 230], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['TOSNA2J', ["34L","34R"], [['TOSNA', 20000, undefined, undefined], ['DATAL', undefined, undefined, undefined], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['KATED', undefined, undefined, undefined], ['LOSEN', 11000, 11000, 230], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['VEDED2L', ["34L","34R"], [['VEDED', 18000, 18000, undefined], ['VELAM', undefined, undefined, 250], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['KATED', undefined, undefined, undefined], ['LOSEN', 11000, 11000, 230], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['ALKAN2R', ["34L","34R"], [['ALKAN', 20000, undefined, undefined], ['GETOV', undefined, undefined, 250], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['HAYYA2R', ["34L","34R"], [['HAYYA', 21000, undefined, undefined], ['VELAM', 19000, undefined, undefined], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['ORLEK1R', ["34L","34R"], [['ORLEK', 21000, undefined, undefined], ['GINTO', undefined, undefined, undefined], ['LAGNO', 10000, 10000, undefined], ['NOLMA', undefined, undefined, 230], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['TOSNA2V', ["34L","34R"], [['TOSNA', 20000, undefined, undefined], ['DATAL', undefined, undefined, undefined], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['VEDED2R', ["34L","34R"], [['VEDED', 18000, 18000, undefined], ['VELAM', undefined, undefined, 250], ['VUTAN', 18000, undefined, undefined], ['TUDOM', undefined, undefined, undefined], ['GETOV', undefined, undefined, undefined], ['RESAR', undefined, undefined, undefined], ['SILBI', undefined, undefined, undefined], ['NORMU', undefined, undefined, 250], ['DATAL', undefined, undefined, 250], ['LABEX', undefined, undefined, undefined], ['KUBAR', undefined, undefined, undefined], ['OXAGO', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['ALKAN2V', ["34L","34R"], [['ALKAN', 20000, undefined, undefined], ['SENKI', undefined, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['HAYYA2V', ["34L","34R"], [['HAYYA', 21000, undefined, undefined], ['VELAM', 19000, undefined, undefined], ['VUTAN', 18000, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['VEDED2V', ["34L","34R"], [['VEDED', 18000, 18000, undefined], ['VELAM', undefined, undefined, 250], ['VUTAN', 18000, undefined, undefined], ['LUBAK', undefined, undefined, undefined], ['BAYAN', 13000, undefined, undefined], ['EGNUG', 8000, 9000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['LAEEB1R', ["34L","34R"], [['LAEEB', undefined, undefined, undefined], ['EMEXA', 13000, 13000, undefined], ['AFNAN', 11000, undefined, undefined], ['EMALO', undefined, undefined, undefined], ['MUTLI', undefined, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', 7000, 7000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['TOSNA2R', ["34L","34R"], [['TOSNA', 20000, undefined, undefined], ['KUVLA', undefined, undefined, undefined], ['DINEX', undefined, undefined, 250], ['KIVAM', undefined, 12000, undefined], ['AFNAN', 11000, undefined, undefined], ['EMALO', undefined, undefined, undefined], ['MUTLI', undefined, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', 7000, 7000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['TOVOX2R', ["34L","34R"], [['TOVOX', 18000, 18000, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, 12000, 250], ['AFNAN', 11000, undefined, undefined], ['EMALO', undefined, undefined, undefined], ['MUTLI', undefined, undefined, undefined], ['LOVET', 7000, 7000, undefined], ['EGNUG', 7000, 7000, undefined], ['MISOX', 6000, undefined, undefined], ['SIDMU', undefined, undefined, undefined], ['LOVAN', 4000, undefined, undefined], ['MUXED', 2500, 3500, 220]]],
  ['LAEEB1J', ["34L","34R"], [['LAEEB', undefined, undefined, undefined], ['GOKNI', 13000, undefined, undefined], ['GINTO', undefined, undefined, undefined], ['LAGNO', 10000, 10000, undefined], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['LAEEB1L', ["34L","34R"], [['LAEEB', undefined, undefined, undefined], ['EMEXA', 13000, 13000, undefined], ['MIVAL', undefined, undefined, undefined], ['KUTER', undefined, undefined, undefined], ['NONBA', 6000, 6000, undefined], ['KINAP', undefined, undefined, 220], ['KIPIK', 6000, 6000, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['ORLEK1L', ["34L","34R"], [['ORLEK', 21000, undefined, undefined], ['GINTO', undefined, undefined, undefined], ['LAGNO', 10000, 10000, undefined], ['KIPIK', undefined, undefined, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['TOSNA2L', ["34L","34R"], [['TOSNA', 20000, undefined, undefined], ['KUVLA', undefined, undefined, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, undefined, undefined], ['IMTAL', undefined, undefined, undefined], ['KIPEM', 11000, 12000, undefined], ['EMEXA', 10000, 10000, undefined], ['MIVAL', undefined, undefined, undefined], ['KUTER', undefined, undefined, undefined], ['NONBA', 6000, 6000, undefined], ['KINAP', undefined, undefined, 220], ['KIPIK', 6000, 6000, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
  ['TOVOX2L', ["34L","34R"], [['TOVOX', 18000, 18000, undefined], ['DINEX', undefined, undefined, undefined], ['KIVAM', undefined, undefined, undefined], ['IMTAL', undefined, undefined, undefined], ['KIPEM', 11000, 12000, undefined], ['EMEXA', 10000, 10000, undefined], ['MIVAL', undefined, undefined, undefined], ['KUTER', undefined, undefined, undefined], ['NONBA', 6000, 6000, undefined], ['KINAP', undefined, undefined, 220], ['KIPIK', 6000, 6000, undefined], ['SOMAP', undefined, undefined, undefined], ['PURIN', undefined, undefined, undefined], ['DASIK', 2500, 3500, 220]]],
];

export const DOHA_PUBLISHED_PROCEDURE_PACK: PublishedProcedurePack = {
  airportId: 'doh',
  packVersion: '2026.08.16',
  referenceCycle: 'Qatar eAIP AIRAC AMDT 04/2026 · OTHH STAR issue 02/2026',
  effectiveFrom: '2026-04-16',
  generatedFrom: 'QCAA eAIP · OTHH RNP 1 STAR tabular coding and ENR 4.4 WGS-84 waypoint data',
  procedures: dohaRouteSpecs.map(([id, runwayIds, fixes]) => dohaArrival(id, runwayIds, fixes)),
  sources: [
    {
      publisher: 'Qatar Civil Aviation Authority',
      title: 'Qatar eAIS Package — AIRAC Amendment 04/2026',
      url: 'https://aim.gov.qa/eaip/2026-04-16-AIRAC/html/index-en-GB.html',
      purpose: 'Current published package and effective-date reference',
      accessedOn: ACCESSED_ON,
    },
    {
      publisher: 'Qatar Civil Aviation Authority',
      title: 'OTHH AD 2 — Hamad International',
      url: 'https://aim.gov.qa/eaip/2026-04-16-AIRAC/html/eAIP/AD-2.OTHH-en-GB.html',
      purpose: 'ARP, elevation, runway geometry and all current RNP STAR chart/coding-table links',
      accessedOn: ACCESSED_ON,
    },
    {
      publisher: 'Qatar Civil Aviation Authority',
      title: 'ENR 4.4 — Name-code designators for significant points',
      url: 'https://aim.gov.qa/eaip/2026-04-16-AIRAC/html/eAIP/ENR-4.4-en-GB.html',
      purpose: 'WGS-84 coordinates for every represented STAR waypoint',
      accessedOn: ACCESSED_ON,
    },
    {
      publisher: 'Qatar Civil Aviation Authority',
      title: 'AIC A 08/2025 — OTHH STAR issuance and planning guidance',
      url: 'https://www.aim.gov.qa/eaip/2025-10-02-AIRAC/html/eAIC/eAIC-2025-08-A-en-GB.html',
      purpose: 'Peak/off-peak trombone sequencing and tactical track-shortening concept',
      accessedOn: ACCESSED_ON,
    },
  ],
  gameOnlyNotice: 'All 41 current OTHH RNP STAR identities, full tabular waypoint orders and represented altitude/speed constraints are retained. WGS-84 geometry is uniformly projected into the compact tactical sector and is not for navigation.',
};
